export const START_API_CALL = 'START_API_CALL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';
